# Generated by Django 2.0.13 on 2020-01-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='tag',
            field=models.ManyToManyField(to='tag.Tag', verbose_name='태그'),
        ),
    ]
